### ISSUE TITLE
cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by 0xisk** [authereum/starkware-walletconnect-example#1]
Hi, 
So I was exploring the dapp example for connecting wallets and makings txs with StarkEx on Ropsten. 

And I got the following error when I try to execute the first two transactions Register, and Deposit. 

- ![pic-selected-210701-1534-11](https://user-images.githubusercontent.com/36774944/124133954-a132d980-da82-11eb-980a-bb88550bee13.png)

- ![pic-selected-210701-1540-14](https://user-images.githubusercontent.com/36774944/124134051-b90a5d80-da82-11eb-9d25-933e58b44b65.png)

And got another error when calling Transfer With Fees, Limit Order With Fees, and Withdraw With Fees. 

- ![pic-selected-210701-1542-35](https://user-images.githubusercontent.com/36774944/124134356-0be41500-da83-11eb-8d0b-8aa17ddd66d6.png)
 
- ![pic-selected-210701-1542-17](https://user-images.githubusercontent.com/36774944/124134326-01c21680-da83-11eb-9f30-4c949ca36744.png)

- ![pic-selected-210701-1541-51](https://user-images.githubusercontent.com/36774944/124134286-f66eeb00-da82-11eb-99a4-4cc66db226f7.png)

Sorry I used screenshots for issuing the errors since I couldn't copy and paste the errors from the Alert form. 

Would appreciate your help a lot, thanks.

**Comment by miguelmota** [comment]
@iskanderandrews unfortunately this repo is no longer maintained. 

Your best bet is to get in touch with devs from starkware or ask in the starkware discord [support channel](https://discord.com/channels/793094838509764618/793094838987128844).

Closing issue since this repo will now be archived.
